export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  ADAPTER_NOT_IMPLEMENTED = 'ADAPTER_NOT_IMPLEMENTED',
  ACTION_BUILD_NOT_CONFIGURED = 'ACTION_BUILD_NOT_CONFIGURED',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  POLICY_BLOCKED = 'POLICY_BLOCKED',
  RELAYER_ERROR = 'RELAYER_ERROR',
  INVALID_STATE = 'INVALID_STATE',
}
